// <auto-generated />
using LoLStats.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LoLStats.Migrations
{
    [DbContext(typeof(LoLStatsContext))]
    [Migration("20190727131242_Seila2")]
    partial class Seila2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LoLStats.Models.Perfil", b =>
                {
                    b.Property<string>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("perfil_id")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LeaguePoints")
                        .HasColumnName("pontos_liga");

                    b.Property<int>("Losses")
                        .HasColumnName("derrotas");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("QueueType")
                        .HasColumnName("fila_ranqueada")
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Rank")
                        .HasColumnName("divisao")
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Regiao")
                        .HasColumnName("regiao")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Tier")
                        .HasColumnName("elo")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Wins")
                        .HasColumnName("vitorias");

                    b.HasKey("AccountId");

                    b.ToTable("perfil");
                });
#pragma warning restore 612, 618
        }
    }
}
